# Generated by Django 5.0.4 on 2024-05-08 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=500)),
                ('breed', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('date_of_birth', models.DateField()),
                ('fixed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
