# Generated by Django 5.0.4 on 2024-06-23 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demos', to=settings.AUTH_USER_MODEL),
        ),
    ]
