# Generated by Django 5.0.4 on 2024-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_demo_content_alter_demo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(max_length=50),
        ),
    ]
