# Generated by Django 5.0.4 on 2024-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pet_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
