# Generated by Django 5.0.4 on 2024-06-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='length',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
    ]
