# Generated by Django 5.0.4 on 2024-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pet_age_remove_pet_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
