# Generated by Django 5.0.4 on 2024-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pet_age_pet_breed_pet_length_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
