# Generated by Django 5.0.4 on 2024-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pet_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='pet',
            name='fixed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
