# Generated by Django 5.0.4 on 2024-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_remove_appointment_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
