# Generated by Django 5.0.4 on 2024-06-24 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shift_status_remove_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
        migrations.CreateModel(
            name='Anoymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('time', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shift')),
            ],
        ),
    ]
