# Generated by Django 5.0.4 on 2024-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_owner_id_appointment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='verified',
            field=models.CharField(default='Not verified', max_length=50),
        ),
    ]
