# Generated by Django 5.0.4 on 2024-06-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_pet_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Check up', max_length=50),
        ),
    ]
