# Generated by Django 5.0.4 on 2024-06-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='Appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.appointment'),
        ),
    ]
