# Generated by Django 5.0.4 on 2024-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_pet_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Appointment',
            new_name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_id',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
