# Generated by Django 5.0.4 on 2024-06-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_appointment_pet_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='appointment',
        ),
    ]
