# Generated by Django 5.0.4 on 2024-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Check up', max_length=50),
        ),
    ]
