# Generated by Django 5.0.4 on 2024-06-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_appointment_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
