# Generated by Django 5.0.4 on 2024-06-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_appointment_date_created_appointment_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
