# Generated by Django 5.0.4 on 2024-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='7:00:00', max_length=50),
        ),
    ]
