# Generated by Django 5.0.4 on 2024-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_appointment_pet_id_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='length',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads/pet_images/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
