# Generated by Django 5.0.4 on 2024-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_pet_age_remove_pet_length_remove_pet_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='Unindentified', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='uploads/pet_images/default.png', upload_to='uploads/pet_images/'),
        ),
    ]
