# Generated by Django 5.0.4 on 2024-06-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_image_pet_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_image',
            new_name='picture',
        ),
    ]
