# Generated by Django 5.0.4 on 2024-06-28 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_picture_pet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprocess', 'In-Process'), ('canceled', 'Canceled'), ('complete', 'Completed')], default='pending', max_length=50),
        ),
        migrations.RemoveField(
            model_name='service',
            name='addition_fee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='verified',
            field=models.CharField(default='unverified', max_length=50),
        ),
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(default='Today', max_length=100)),
                ('time', models.CharField(default='7:00:00', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprocess', 'In-Process'), ('canceled', 'Canceled'), ('complete', 'Completed')], default='pending', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('addition_fee', models.FloatField(blank=True, default='0')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_result', to='api.appointment')),
            ],
        ),
        migrations.DeleteModel(
            name='Anoymous',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
