# Generated by Django 5.0.4 on 2024-06-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_appointment_pet_id_pet_appointment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pet'),
        ),
    ]
