# Generated by Django 5.0.4 on 2024-06-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pet'),
        ),
    ]
