# Generated by Django 5.0.4 on 2024-06-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_appointment_pet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('doctor_image', models.ImageField(default='uploads/pet_images/default.png', upload_to='uploads/doctors/')),
                ('experience', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shift'),
        ),
        migrations.AlterField(
            model_name='result',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_result', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='shift',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
    ]
