# Generated by Django 5.0.4 on 2024-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_doctor_appointment_estimated_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='file',
            field=models.ImageField(blank=True, default='uploads/pet_images/default.png', upload_to='uploads/pet_images/'),
        ),
    ]
