# Generated by Django 5.0.4 on 2024-07-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_pet_verified_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='doctor',
        ),
    ]
